/**
 * The line that greets an empty chat.
 *
 * A single fixed sentence makes every new chat look like the one before it.
 * These are drawn from a set instead, picked from the chat's own id so the
 * line holds still while it is being read and a new chat brings a new one.
 *
 * They are kept here rather than in the translation table because that table
 * holds one string per key, and each language needs two dozen. Each set keeps
 * the same register as the rest of that language's interface: `vous` in
 * French, `du` in German, the polite forms in Japanese and Korean.
 *
 * Keep them short. They are set in large uppercase type, so a long sentence
 * wraps and stops reading as a greeting.
 */

export const GREETINGS: Record<string, string[]> = {
  en: [
    "How can I help you?",
    "What's on your mind?",
    "Where shall we start?",
    "What are you working on?",
    "Ready when you are",
    "Ask me anything",
    "What can I do for you?",
    "What shall we build?",
    "What do you need?",
    "Let's get to work",
    "What's the task?",
    "Fire away",
    "I'm listening",
    "What's next?",
    "What shall we look at?",
    "Got a question?",
    "Tell me what you need",
    "Start anywhere",
    "What are we solving?",
    "Say the word",
    "What's the plan?",
    "What's puzzling you?",
    "Ready to dig in?",
    "Type away",
  ],
  fr: [
    "Comment puis-je vous aider ?",
    "À quoi pensez-vous ?",
    "Par où commençons-nous ?",
    "Sur quoi travaillez-vous ?",
    "Quand vous voulez",
    "Posez-moi vos questions",
    "Que puis-je faire pour vous ?",
    "Que construit-on ?",
    "De quoi avez-vous besoin ?",
    "Au travail",
    "Quelle est la tâche ?",
    "Allez-y",
    "Je vous écoute",
    "Et ensuite ?",
    "Que regardons-nous ?",
    "Une question ?",
    "Dites-moi ce qu'il vous faut",
    "Commencez où vous voulez",
    "Quel problème résout-on ?",
    "Dites un mot",
    "Quel est le plan ?",
    "Qu'est-ce qui vous bloque ?",
    "On s'y met ?",
    "À vous de jouer",
  ],
  es: [
    "¿Cómo puedo ayudarte?",
    "¿En qué estás pensando?",
    "¿Por dónde empezamos?",
    "¿En qué estás trabajando?",
    "Cuando quieras",
    "Pregúntame lo que sea",
    "¿Qué puedo hacer por ti?",
    "¿Qué construimos?",
    "¿Qué necesitas?",
    "Manos a la obra",
    "¿Cuál es la tarea?",
    "Adelante",
    "Te escucho",
    "¿Y ahora qué?",
    "¿Qué miramos?",
    "¿Alguna pregunta?",
    "Dime qué necesitas",
    "Empieza por donde quieras",
    "¿Qué problema resolvemos?",
    "Tú dirás",
    "¿Cuál es el plan?",
    "¿Qué se te resiste?",
    "¿Empezamos?",
    "Escribe cuando quieras",
  ],
  de: [
    "Wie kann ich dir helfen?",
    "Woran denkst du?",
    "Womit fangen wir an?",
    "Woran arbeitest du?",
    "Leg einfach los",
    "Frag mich alles",
    "Was kann ich für dich tun?",
    "Was bauen wir?",
    "Was brauchst du?",
    "An die Arbeit",
    "Was steht an?",
    "Nur zu",
    "Ich höre zu",
    "Was kommt als Nächstes?",
    "Was schauen wir uns an?",
    "Eine Frage?",
    "Sag mir, was du brauchst",
    "Fang an, wo du willst",
    "Was lösen wir?",
    "Sag Bescheid",
    "Wie ist der Plan?",
    "Woran hängt es?",
    "Sollen wir loslegen?",
    "Schreib einfach",
  ],
  it: [
    "Come posso aiutarti?",
    "A cosa stai pensando?",
    "Da dove cominciamo?",
    "A cosa stai lavorando?",
    "Quando vuoi",
    "Chiedimi quello che vuoi",
    "Cosa posso fare per te?",
    "Cosa costruiamo?",
    "Di cosa hai bisogno?",
    "Al lavoro",
    "Qual è il compito?",
    "Vai pure",
    "Ti ascolto",
    "E adesso?",
    "Cosa guardiamo?",
    "Hai una domanda?",
    "Dimmi cosa ti serve",
    "Comincia da dove vuoi",
    "Che problema risolviamo?",
    "Basta una parola",
    "Qual è il piano?",
    "Cosa non torna?",
    "Cominciamo?",
    "Scrivi pure",
  ],
  pt: [
    "Como posso ajudar?",
    "Em que está a pensar?",
    "Por onde começamos?",
    "Em que está a trabalhar?",
    "Quando quiser",
    "Pergunte-me o que quiser",
    "O que posso fazer por si?",
    "O que vamos construir?",
    "Do que precisa?",
    "Mãos à obra",
    "Qual é a tarefa?",
    "Diga lá",
    "Estou a ouvir",
    "E a seguir?",
    "O que vamos ver?",
    "Alguma pergunta?",
    "Diga-me do que precisa",
    "Comece por onde quiser",
    "Que problema resolvemos?",
    "É só dizer",
    "Qual é o plano?",
    "O que o está a travar?",
    "Vamos a isto?",
    "Escreva quando quiser",
  ],
  nl: [
    "Hoe kan ik je helpen?",
    "Waar denk je aan?",
    "Waar beginnen we?",
    "Waar werk je aan?",
    "Begin wanneer je wilt",
    "Vraag me alles",
    "Wat kan ik voor je doen?",
    "Wat gaan we bouwen?",
    "Wat heb je nodig?",
    "Aan de slag",
    "Wat is de taak?",
    "Ga je gang",
    "Ik luister",
    "Wat nu?",
    "Waar kijken we naar?",
    "Heb je een vraag?",
    "Zeg maar wat je nodig hebt",
    "Begin waar je wilt",
    "Wat lossen we op?",
    "Zeg het maar",
    "Wat is het plan?",
    "Waar loop je op vast?",
    "Zullen we beginnen?",
    "Typ maar raak",
  ],
  ru: [
    "Чем могу помочь?",
    "О чём думаете?",
    "С чего начнём?",
    "Над чем работаете?",
    "Начинайте, когда готовы",
    "Спрашивайте о чём угодно",
    "Что я могу для вас сделать?",
    "Что будем создавать?",
    "Что вам нужно?",
    "За работу",
    "Какая задача?",
    "Задавайте вопрос",
    "Слушаю вас",
    "Что дальше?",
    "На что посмотрим?",
    "Есть вопрос?",
    "Скажите, что нужно",
    "Начните с чего угодно",
    "Какую задачу решаем?",
    "Только скажите",
    "Какой план?",
    "Что не получается?",
    "Приступим?",
    "Пишите",
  ],
  zh: [
    "我能怎么帮助你？",
    "你在想什么？",
    "我们从哪里开始？",
    "你在做什么项目？",
    "随时可以开始",
    "有什么尽管问",
    "我能为你做什么？",
    "我们来做点什么？",
    "你需要什么？",
    "开始干活吧",
    "这次的任务是什么？",
    "请说",
    "我在听",
    "接下来呢？",
    "我们来看看什么？",
    "有问题吗？",
    "告诉我你需要什么",
    "从哪里开始都行",
    "我们要解决什么？",
    "一句话的事",
    "计划是什么？",
    "卡在哪里了？",
    "要开始了吗？",
    "尽管输入",
  ],
  ja: [
    "どのようにお手伝いできますか？",
    "何をお考えですか？",
    "どこから始めましょうか？",
    "何に取り組んでいますか？",
    "いつでもどうぞ",
    "何でも聞いてください",
    "何かお役に立てますか？",
    "何を作りましょうか？",
    "何が必要ですか？",
    "さあ、始めましょう",
    "今回の課題は？",
    "どうぞお話しください",
    "聞いています",
    "次は何を？",
    "何を見てみましょうか？",
    "質問はありますか？",
    "必要なものを教えてください",
    "どこからでもどうぞ",
    "何を解決しましょうか？",
    "お申し付けください",
    "計画はありますか？",
    "どこで詰まっていますか？",
    "始めましょうか？",
    "お好きに入力してください",
  ],
  ko: [
    "무엇을 도와드릴까요?",
    "무슨 생각을 하고 계신가요?",
    "어디서부터 시작할까요?",
    "어떤 작업을 하고 계신가요?",
    "준비되시면 시작하세요",
    "무엇이든 물어보세요",
    "무엇을 해드릴까요?",
    "무엇을 만들어 볼까요?",
    "무엇이 필요하신가요?",
    "이제 시작해 볼까요",
    "이번 작업은 무엇인가요?",
    "편하게 말씀하세요",
    "듣고 있습니다",
    "다음은 무엇인가요?",
    "무엇을 살펴볼까요?",
    "질문이 있으신가요?",
    "필요한 것을 말씀해 주세요",
    "어디서부터든 시작하세요",
    "무엇을 해결할까요?",
    "말씀만 하세요",
    "계획이 어떻게 되나요?",
    "어디서 막히셨나요?",
    "시작해 볼까요?",
    "자유롭게 입력하세요",
  ],
  ar: [
    "كيف يمكنني مساعدتك؟",
    "بماذا تفكر؟",
    "من أين نبدأ؟",
    "على ماذا تعمل؟",
    "ابدأ متى شئت",
    "اسألني أي شيء",
    "ماذا يمكنني أن أفعل لك؟",
    "ماذا سنبني؟",
    "ماذا تحتاج؟",
    "لنبدأ العمل",
    "ما هي المهمة؟",
    "تفضل",
    "أنا أستمع",
    "وماذا بعد؟",
    "ماذا سنراجع؟",
    "هل لديك سؤال؟",
    "أخبرني بما تحتاج",
    "ابدأ من أي مكان",
    "ما المشكلة التي نحلها؟",
    "كلمة واحدة تكفي",
    "ما هي الخطة؟",
    "أين تعثرت؟",
    "هل نبدأ؟",
    "اكتب ما تشاء",
  ],
};

/** How many each language is expected to carry, so none quietly falls behind. */
export const GREETING_COUNT = 24;

const FALLBACK = "en";

/** The greetings for a language, falling back to English for anything else. */
export function greetingsFor(language: string): string[] {
  const pool = GREETINGS[language];
  return pool && pool.length > 0 ? pool : GREETINGS[FALLBACK];
}

/**
 * Spreads similar seeds across the set. Chat ids differ by only a character or
 * two, so taking the first of them would land on the same greeting every time.
 */
function scatter(seed: string): number {
  let value = 5381;
  for (let index = 0; index < seed.length; index++) {
    value = ((value << 5) + value) ^ seed.charCodeAt(index);
  }
  return value >>> 0;
}

/**
 * The greeting for one chat. The same chat always gets the same line, so it
 * does not change under the reader; a different chat gets a different one.
 */
export function pickGreeting(language: string, seed: string): string {
  const pool = greetingsFor(language);
  return pool[scatter(seed ?? "") % pool.length];
}
